FROM python:3.11-slim



# Install required system dependencies
RUN apt-get update && apt-get install -y \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*


# Set the working directory in the container
WORKDIR /app

# Copy and install Python dependencies
COPY requirements.txt .
# RUN pip3 install psycopg2
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .


RUN dos2unix /*.sh
RUN dos2unix /scripts/*.sh


# Default command
CMD ["sh", "entrypoint.sh"]

