FROM python:3.11-slim



# Install required system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libfreetype6-dev \
    libjpeg-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libraqm-dev \
    zlib1g-dev \
    pkg-config \
    curl \
    cron \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*


# Copy and install Python dependencies
COPY requirements.txt .
# RUN pip3 install psycopg2
RUN pip install --no-cache-dir -r requirements.txt


# Copy project files into the container
COPY . .


RUN dos2unix /scripts/*.sh

