# Generated by Django 5.2.5 on 2025-11-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='nid_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
