# Generated by Django 5.2.8 on 2025-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_useraddress_city_alter_useraddress_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
    ]
