# Generated by Django 5.1.2 on 2024-11-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='user',
        ),
    ]
