# Generated by Django 5.1.2 on 2024-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='after_transaction_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
