# Generated by Django 5.1.2 on 2024-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='after_transaction_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
