# Generated by Django 5.1.2 on 2024-11-22 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0007_loan_approve_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2B',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transactions.transaction')),
                ('receiver', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_b2b', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_b2b', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Transactions.transaction',),
        ),
    ]
