# Generated by Django 5.1.2 on 2024-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0009_alter_transaction_after_transaction_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2b',
            name='b2b_money',
            field=models.BooleanField(default=1, null=1),
            preserve_default=1,
        ),
    ]
