# Generated by Django 5.2.5 on 2025-11-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0011_transaction_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
    ]
