# Generated by Django 5.2.5 on 2025-11-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0012_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=115.0, max_digits=12),
        ),
    ]
